import { Transaction } from "@/lib/types";
import { daysFromNow } from "./dates";

export const transactions: Transaction[] = [
  // ---------- Padaria Pão Nosso ----------
  { id: "paonosso-t1", companyId: "company-paonosso", type: "receivable", description: "Venda mensal - Café Bom Dia", amount: 1850, dueDate: daysFromNow(-15), paidAt: daysFromNow(-15), status: "paid", categoryId: "paonosso-cat-vendas", contactId: "paonosso-contact-3" },
  { id: "paonosso-t2", companyId: "company-paonosso", type: "receivable", description: "Encomenda de bolos - Doce Encontro", amount: 640, dueDate: daysFromNow(-3), paidAt: daysFromNow(-3), status: "paid", categoryId: "paonosso-cat-servicos", contactId: "paonosso-contact-4" },
  { id: "paonosso-t3", companyId: "company-paonosso", type: "receivable", description: "Venda mensal - Café Bom Dia", amount: 1920, dueDate: daysFromNow(15), paidAt: null, status: "pending", categoryId: "paonosso-cat-vendas", contactId: "paonosso-contact-3" },
  { id: "paonosso-t4", companyId: "company-paonosso", type: "receivable", description: "Encomenda de festa - Doce Encontro", amount: 980, dueDate: daysFromNow(-5), paidAt: null, status: "overdue", categoryId: "paonosso-cat-servicos", contactId: "paonosso-contact-4" },
  { id: "paonosso-t5", companyId: "company-paonosso", type: "receivable", description: "Venda balcão (consolidado semana)", amount: 2340, dueDate: daysFromNow(3), paidAt: null, status: "pending", categoryId: "paonosso-cat-outras-receitas", contactId: "paonosso-contact-3" },
  { id: "paonosso-t6", companyId: "company-paonosso", type: "payable", description: "Compra de farinha e insumos", amount: 1200, dueDate: daysFromNow(-10), paidAt: daysFromNow(-10), status: "paid", categoryId: "paonosso-cat-fornecedores", contactId: "paonosso-contact-2" },
  { id: "paonosso-t7", companyId: "company-paonosso", type: "payable", description: "Compra de laticínios e ovos", amount: 780, dueDate: daysFromNow(-2), paidAt: null, status: "overdue", categoryId: "paonosso-cat-fornecedores", contactId: "paonosso-contact-1" },
  { id: "paonosso-t8", companyId: "company-paonosso", type: "payable", description: "Aluguel do ponto comercial", amount: 3200, dueDate: daysFromNow(5), paidAt: null, status: "pending", categoryId: "paonosso-cat-aluguel", contactId: "paonosso-contact-1" },
  { id: "paonosso-t9", companyId: "company-paonosso", type: "payable", description: "Salários da equipe", amount: 5400, dueDate: daysFromNow(8), paidAt: null, status: "pending", categoryId: "paonosso-cat-salarios", contactId: "paonosso-contact-1" },
  { id: "paonosso-t10", companyId: "company-paonosso", type: "payable", description: "Impostos (Simples Nacional)", amount: 890, dueDate: daysFromNow(-1), paidAt: daysFromNow(-1), status: "paid", categoryId: "paonosso-cat-impostos", contactId: "paonosso-contact-1" },
  { id: "paonosso-t11", companyId: "company-paonosso", type: "payable", description: "Anúncios em redes sociais", amount: 350, dueDate: daysFromNow(10), paidAt: null, status: "pending", categoryId: "paonosso-cat-marketing", contactId: "paonosso-contact-1" },

  // ---------- Oficina Mecânica Rota Certa ----------
  { id: "rotacerta-t1", companyId: "company-rotacerta", type: "receivable", description: "Revisão de frota - Transportadora Veloz", amount: 6800, dueDate: daysFromNow(-20), paidAt: daysFromNow(-20), status: "paid", categoryId: "rotacerta-cat-servicos", contactId: "rotacerta-contact-3" },
  { id: "rotacerta-t2", companyId: "company-rotacerta", type: "receivable", description: "Manutenção preventiva - Locadora Rodas & Cia", amount: 4300, dueDate: daysFromNow(-6), paidAt: daysFromNow(-6), status: "paid", categoryId: "rotacerta-cat-servicos", contactId: "rotacerta-contact-4" },
  { id: "rotacerta-t3", companyId: "company-rotacerta", type: "receivable", description: "Revisão de frota - Transportadora Veloz", amount: 7100, dueDate: daysFromNow(12), paidAt: null, status: "pending", categoryId: "rotacerta-cat-servicos", contactId: "rotacerta-contact-3" },
  { id: "rotacerta-t4", companyId: "company-rotacerta", type: "receivable", description: "Troca de suspensão - Locadora Rodas & Cia", amount: 2150, dueDate: daysFromNow(-4), paidAt: null, status: "overdue", categoryId: "rotacerta-cat-servicos", contactId: "rotacerta-contact-4" },
  { id: "rotacerta-t5", companyId: "company-rotacerta", type: "receivable", description: "Serviços avulsos (balcão)", amount: 1580, dueDate: daysFromNow(2), paidAt: null, status: "pending", categoryId: "rotacerta-cat-outras-receitas", contactId: "rotacerta-contact-3" },
  { id: "rotacerta-t6", companyId: "company-rotacerta", type: "payable", description: "Compra de peças e autopeças", amount: 3900, dueDate: daysFromNow(-8), paidAt: daysFromNow(-8), status: "paid", categoryId: "rotacerta-cat-fornecedores", contactId: "rotacerta-contact-1" },
  { id: "rotacerta-t7", companyId: "company-rotacerta", type: "payable", description: "Óleos e lubrificantes", amount: 1450, dueDate: daysFromNow(-3), paidAt: null, status: "overdue", categoryId: "rotacerta-cat-fornecedores", contactId: "rotacerta-contact-2" },
  { id: "rotacerta-t8", companyId: "company-rotacerta", type: "payable", description: "Aluguel da oficina", amount: 4500, dueDate: daysFromNow(6), paidAt: null, status: "pending", categoryId: "rotacerta-cat-aluguel", contactId: "rotacerta-contact-1" },
  { id: "rotacerta-t9", companyId: "company-rotacerta", type: "payable", description: "Salários da equipe técnica", amount: 9800, dueDate: daysFromNow(9), paidAt: null, status: "pending", categoryId: "rotacerta-cat-salarios", contactId: "rotacerta-contact-1" },
  { id: "rotacerta-t10", companyId: "company-rotacerta", type: "payable", description: "Impostos (Simples Nacional)", amount: 2100, dueDate: daysFromNow(-1), paidAt: daysFromNow(-1), status: "paid", categoryId: "rotacerta-cat-impostos", contactId: "rotacerta-contact-1" },
  { id: "rotacerta-t11", companyId: "company-rotacerta", type: "payable", description: "Divulgação em rádio local", amount: 600, dueDate: daysFromNow(14), paidAt: null, status: "pending", categoryId: "rotacerta-cat-marketing", contactId: "rotacerta-contact-1" },

  // ---------- Distribuidora Boa Vista ----------
  { id: "boavista-t1", companyId: "company-boavista", type: "receivable", description: "Pedido mensal - Mercadinho Boa Esperança", amount: 5200, dueDate: daysFromNow(-12), paidAt: daysFromNow(-12), status: "paid", categoryId: "boavista-cat-vendas", contactId: "boavista-contact-2" },
  { id: "boavista-t2", companyId: "company-boavista", type: "receivable", description: "Pedido especial - Loja Estilo & Cia", amount: 3100, dueDate: daysFromNow(-9), paidAt: null, status: "overdue", categoryId: "boavista-cat-vendas", contactId: "boavista-contact-3" },
  { id: "boavista-t3", companyId: "company-boavista", type: "receivable", description: "Pedido mensal - Mercadinho Boa Esperança", amount: 4800, dueDate: daysFromNow(-6), paidAt: null, status: "overdue", categoryId: "boavista-cat-vendas", contactId: "boavista-contact-2" },
  { id: "boavista-t4", companyId: "company-boavista", type: "receivable", description: "Frete e distribuição avulsa", amount: 950, dueDate: daysFromNow(4), paidAt: null, status: "pending", categoryId: "boavista-cat-outras-receitas", contactId: "boavista-contact-3" },
  { id: "boavista-t5", companyId: "company-boavista", type: "payable", description: "Compra de mercadorias têxteis", amount: 6400, dueDate: daysFromNow(-14), paidAt: daysFromNow(-14), status: "paid", categoryId: "boavista-cat-fornecedores", contactId: "boavista-contact-1" },
  { id: "boavista-t6", companyId: "company-boavista", type: "payable", description: "Reposição de estoque", amount: 3700, dueDate: daysFromNow(-4), paidAt: null, status: "overdue", categoryId: "boavista-cat-fornecedores", contactId: "boavista-contact-1" },
  { id: "boavista-t7", companyId: "company-boavista", type: "payable", description: "Aluguel do galpão", amount: 2800, dueDate: daysFromNow(-2), paidAt: null, status: "overdue", categoryId: "boavista-cat-aluguel", contactId: "boavista-contact-1" },
  { id: "boavista-t8", companyId: "company-boavista", type: "payable", description: "Salários da equipe", amount: 4100, dueDate: daysFromNow(-1), paidAt: null, status: "overdue", categoryId: "boavista-cat-salarios", contactId: "boavista-contact-1" },
  { id: "boavista-t9", companyId: "company-boavista", type: "payable", description: "Impostos (Simples Nacional)", amount: 1300, dueDate: daysFromNow(-16), paidAt: daysFromNow(-16), status: "paid", categoryId: "boavista-cat-impostos", contactId: "boavista-contact-1" },
];
